### PR TITLE
Fix build with current version

### PR DESCRIPTION
**Pull request by elmarco**

### CODE REVIEW

**Comment by sdroege** [comment]
This PR looks reversed. Are you sure you're not using an old version of glib?

See also https://github.com/sdroege/gobject-example-rs/pull/20 for comparison. CC @bilelmoussaoui

**Comment by elmarco** [comment]
I am confused, maybe. What's the way to make sure you are building against latest git ? cargo tree  and check the gir revision?

**Comment by elmarco** [comment]
ok I was not on the latest. sorry

**Comment by sdroege** [comment]
No problem :)

**Comment by bilelmoussaoui** [comment]
We need to add some basic CI or just move this repo to gtk-rs-core

**Comment by sdroege** [comment]
Move it :)

**Pull request closed without merging**
